// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT AppItem

lv_obj_t * ui_AppItem_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_AppItem;
    cui_AppItem = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_AppItem);
    lv_obj_set_width(cui_AppItem, 150);
    lv_obj_set_height(cui_AppItem, 150);
    lv_obj_set_x(cui_AppItem, -412);
    lv_obj_set_y(cui_AppItem, 30);
    lv_obj_set_align(cui_AppItem, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_AppItem, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_appItemImage;
    cui_appItemImage = lv_image_create(cui_AppItem);
    lv_image_set_src(cui_appItemImage, &ui_img_carplaysettings_png);
    lv_obj_set_width(cui_appItemImage, 80);
    lv_obj_set_height(cui_appItemImage, 80);
    lv_obj_set_x(cui_appItemImage, 0);
    lv_obj_set_y(cui_appItemImage, -23);
    lv_obj_set_align(cui_appItemImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_appItemImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_appItemImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_appItemImage, 75);

    lv_obj_t * cui_appItemText;
    cui_appItemText = lv_label_create(cui_AppItem);
    lv_obj_set_width(cui_appItemText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_appItemText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_appItemText, 0);
    lv_obj_set_y(cui_appItemText, 110);
    lv_obj_set_align(cui_appItemText, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_appItemText, "CarPlaySettings");
    lv_obj_set_style_text_color(cui_appItemText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_appItemText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_APPITEM_NUM);
    children[UI_COMP_APPITEM_APPITEM] = cui_AppItem;
    children[UI_COMP_APPITEM_APPITEMIMAGE] = cui_appItemImage;
    children[UI_COMP_APPITEM_APPITEMTEXT] = cui_appItemText;
    lv_obj_add_event_cb(cui_AppItem, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_AppItem, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_AppItem_create_hook(cui_AppItem);
    return cui_AppItem;
}

