// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_APPITEM_H
#define _UI_COMP_APPITEM_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT AppItem
#define UI_COMP_APPITEM_APPITEM 0
#define UI_COMP_APPITEM_APPITEMIMAGE 1
#define UI_COMP_APPITEM_APPITEMTEXT 2
#define _UI_COMP_APPITEM_NUM 3
lv_obj_t * ui_AppItem_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
