/* dvr_images.h — LV_IMG_DECLARE for all DVR image assets */
/* Auto-generated by convert_dvr_images.py */

#ifndef DVR_IMAGES_H
#define DVR_IMAGES_H

#include "lvgl/lvgl.h"

LV_IMG_DECLARE(ui_img_dvr_bg_png);
LV_IMG_DECLARE(ui_img_dvr_list_bg_png);
LV_IMG_DECLARE(ui_img_dvr_icon_png);
LV_IMG_DECLARE(ui_img_dvr_loading_0_png);
LV_IMG_DECLARE(ui_img_dvr_loading_1_png);
LV_IMG_DECLARE(ui_img_dvr_loading_2_png);
LV_IMG_DECLARE(ui_img_dvr_loading_3_png);
LV_IMG_DECLARE(ui_img_dvr_loading_4_png);
LV_IMG_DECLARE(ui_img_dvr_loading_5_png);
LV_IMG_DECLARE(ui_img_dvr_loading_6_png);
LV_IMG_DECLARE(ui_img_dvr_loading_7_png);
LV_IMG_DECLARE(ui_img_dock_bg_png);
LV_IMG_DECLARE(ui_img_dock_selected_png);
LV_IMG_DECLARE(ui_img_line_png);
LV_IMG_DECLARE(ui_img_icon_camera_n_png);
LV_IMG_DECLARE(ui_img_icon_camera_p_png);
LV_IMG_DECLARE(ui_img_icon_playback_n_png);
LV_IMG_DECLARE(ui_img_icon_playback_p_png);
LV_IMG_DECLARE(ui_img_icon_photo_n_png);
LV_IMG_DECLARE(ui_img_icon_photo_p_png);
LV_IMG_DECLARE(ui_img_icon_settings_n_png);
LV_IMG_DECLARE(ui_img_icon_settings_p_png);
LV_IMG_DECLARE(ui_img_icon_view_n_png);
LV_IMG_DECLARE(ui_img_icon_view_p_png);
LV_IMG_DECLARE(ui_img_icon_delete_n_png);
LV_IMG_DECLARE(ui_img_icon_delete_p_png);
LV_IMG_DECLARE(ui_img_list_bg_n_png);
LV_IMG_DECLARE(ui_img_list_bg_p_png);
LV_IMG_DECLARE(ui_img_list_icon_video_n_png);
LV_IMG_DECLARE(ui_img_list_icon_video_p_png);
LV_IMG_DECLARE(ui_img_list_icon_img_n_png);
LV_IMG_DECLARE(ui_img_list_icon_img_p_png);
LV_IMG_DECLARE(ui_img_pop_up_bg_png);
LV_IMG_DECLARE(ui_img_pop_up_btn_n_png);
LV_IMG_DECLARE(ui_img_pop_up_btn_p_png);
LV_IMG_DECLARE(ui_img_settings_btn1_n_png);
LV_IMG_DECLARE(ui_img_settings_btn1_p_png);
LV_IMG_DECLARE(ui_img_settings_btn2_n_png);
LV_IMG_DECLARE(ui_img_settings_btn2_p_png);
LV_IMG_DECLARE(ui_img_settings_btn2w_n_png);
LV_IMG_DECLARE(ui_img_settings_btn2w_p_png);
LV_IMG_DECLARE(ui_img_settings_btn3_n_png);
LV_IMG_DECLARE(ui_img_settings_btn3_p_png);
LV_IMG_DECLARE(ui_img_settings_s_png);
LV_IMG_DECLARE(ui_img_storage_n_png);
LV_IMG_DECLARE(ui_img_storage_p_png);

#endif /* DVR_IMAGES_H */
