// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project
//
// hcn/application/lvgl 最小 UI 模块装配：
//  - videofocusmanager 屏幕导航框架（迁移文档 1.2/1.3 程序流保留）
//  - 仅注册 Home 屏（最小模块）；bt/aa/carplay/rvc 等适配屏未迁入，
//    Home 图标点击 open_app 未注册 App 时由 videofocusmanager 拒绝并记日志
//  - HCN_APP_FULL：Home 屏挂 dashboard_view（MVVM 车辆数据面板）

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////

// Wrapper: bridge SquareLine-generated screen_init with videofocusmanager init_cb
static void home_app_init_cb(lv_obj_t **screen)
{
    ui_Home_screen_init();
    *screen = ui_Home;

#ifdef HCN_APP_FULL
    /* MVVM View 接入：Home 屏构建后挂车辆数据面板（内部 dashboard_vm_init
     * + 订阅 vm emitter，仿 AWTK home_page_init 的 VM→View 装配方）。 */
    dashboard_view_attach(ui_Home);
#endif
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    lv_display_set_color_format(dispp, LV_COLOR_FORMAT_ARGB8888);

    audiofocusmanager_init();
    videofocusmanager_init();

    app_desc_t home_desc = {
        .app_id     = APP_HOME,
        .priority   = APP_PRIORITY_SYSTEM,
        .name       = "Home",
        .init_cb    = home_app_init_cb,
        .destroy_cb = NULL,
    };
    videofocusmanager_register_app(&home_desc);

    videofocusmanager_open_app(APP_HOME);

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}

void ui_destroy(void)
{
    audiofocusmanager_deinit();
    videofocusmanager_deinit();

    ui_Home = NULL;
}
