// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project
//
// hcn/application/lvgl 最小 UI 模块：仅保留 Home 屏与公共装配。
// 完整屏集见 source/packages/application/lvgl_home（迁移 baseline）。

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
#include "fonts/ui_font_chinese_16.h"
#include "frameworks/audiofocusmanager.h"
#include "frameworks/videofocusmanager.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"

/* MVVM lvgl View（HCN_APP_FULL 模式）：车辆数据面板挂接在 Home 屏 */
#ifdef HCN_APP_FULL
#include "screens/dashboard_view.h"
#endif

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_carplaysettings_png);    // assets/carplaysettings.png
LV_IMG_DECLARE(ui_img_carplayapp_png);    // assets/carplayapp.png
LV_IMG_DECLARE(ui_img_androidautosettings_png);    // assets/androidautosettings.png
LV_IMG_DECLARE(ui_img_androidautoapp_png);    // assets/androidautoapp.png
LV_IMG_DECLARE(ui_img_video_png);    // assets/video.png
LV_IMG_DECLARE(ui_img_rvc_car_png);    // assets/rvc_car.png
LV_IMG_DECLARE(ui_img_music_png);    // assets/music.png
LV_IMG_DECLARE(ui_img_picture_png);  // assets/picture.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_btcall_png);    // assets/btcall.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
