// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

/* 最小 UI 模块未迁入 bt/androidauto 适配层：默认关闭，迁入适配层后置 1
 * （CMake 加 -DHCN_APP_HAVE_BT=1 / -DHCN_APP_HAVE_AA=1）恢复原行为。 */
#ifdef HCN_APP_HAVE_BT
#include "bt_app.h"
#endif
#ifdef HCN_APP_HAVE_AA
#include "aa_app.h"
#endif

#include <syslog.h>

#ifdef LVGL_BUILD_CARPLAY
#include "carplayapp_if.h"
#include "carplayapp_ui.h"
#include "carplaysetting_ui.h"
#endif

lv_obj_t * uic_AppItemFlwPage12;
lv_obj_t * uic_AppItemFlwPage11;
lv_obj_t * uic_AppItemFlwPage10;
lv_obj_t * uic_AppItemFlwPage09;
lv_obj_t * uic_AppItemFlwPage08;
lv_obj_t * uic_AppItemFlwPage07;
lv_obj_t * uic_AppItemFlwPage06;
lv_obj_t * uic_AppItemFlwPage05;
lv_obj_t * uic_AppItemFlwPage04;
lv_obj_t * uic_AppItemFlwPage03;
lv_obj_t * uic_AppItemFlwPage02;
lv_obj_t * uic_AppItemFlwPage01;
lv_obj_t * uic_FollowingPage;
lv_obj_t * uic_AppItemTemp04;
lv_obj_t * uic_AppItemBluetooth;
lv_obj_t * uic_AppItemSettings;
lv_obj_t * uic_AppItemPicture;
lv_obj_t * uic_AppItemMusic;
lv_obj_t * uic_AppItemVideo;
lv_obj_t * uic_FixedPage;
lv_obj_t * uic_AppItemTemp02;
lv_obj_t * uic_AppItemTemp01;
lv_obj_t * uic_AppItemAndroidAuto;
lv_obj_t * uic_AppItemAndroidAutoSettings;
lv_obj_t * uic_AppItemCarplayApp;
lv_obj_t * uic_AppItemCarplaySettings;
lv_obj_t * uic_textTemperature;
lv_obj_t * uic_textWeather;
lv_obj_t * uic_textCity;
lv_obj_t * uic_weatherContainer;
lv_obj_t * uic_textDate;
lv_obj_t * uic_textDay;
lv_obj_t * uic_textAMPM;
lv_obj_t * uic_dot;
lv_obj_t * uic_minL;
lv_obj_t * uic_minH;
lv_obj_t * uic_hourL;
lv_obj_t * uic_hourH;
lv_obj_t * uic_TimeAndDataContainer;
lv_obj_t * uic_FirstPage;
lv_obj_t * uic_back_picture;
lv_obj_t * uic_home_picture;
lv_obj_t * uic_TopBarContainer;
lv_obj_t * uic_ContainerHome;
lv_obj_t * uic_Home;
lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_ContainerHome = NULL;
lv_obj_t * ui_TopBarContainer = NULL;
lv_obj_t * ui_homepic = NULL;
lv_obj_t * ui_backpic = NULL;
lv_obj_t * ui_FirstPage = NULL;
lv_obj_t * ui_TimeAndDataContainer = NULL;
lv_obj_t * ui_textTime = NULL;
lv_obj_t * ui_hourH = NULL;
lv_obj_t * ui_hourL = NULL;
lv_obj_t * ui_minH = NULL;
lv_obj_t * ui_minL = NULL;
lv_obj_t * ui_dot = NULL;
lv_obj_t * ui_textAMPM = NULL;
lv_obj_t * ui_textDay = NULL;
lv_obj_t * ui_textDate = NULL;
lv_obj_t * ui_weatherContainer = NULL;
lv_obj_t * ui_ImageWeather = NULL;
lv_obj_t * ui_textCity = NULL;
lv_obj_t * ui_textWeather = NULL;
lv_obj_t * ui_textTemperature = NULL;
lv_obj_t * ui_AppItemCarplaySettings = NULL;
lv_obj_t * ui_AppItemCarplayApp = NULL;
lv_obj_t * ui_AppItemAndroidAutoSettings = NULL;
lv_obj_t * ui_AppItemAndroidAuto = NULL;
lv_obj_t * ui_AppItemTemp01 = NULL;
lv_obj_t * ui_AppItemTemp02 = NULL;
lv_obj_t * ui_FixedPage = NULL;
lv_obj_t * ui_AppItemVideo = NULL;
lv_obj_t * ui_AppItemMusic = NULL;
lv_obj_t * ui_AppItemPicture = NULL;
lv_obj_t * ui_AppItemSettings = NULL;
lv_obj_t * ui_AppItemBluetooth = NULL;
lv_obj_t * ui_AppItemTemp04 = NULL;
lv_obj_t * ui_FollowingPage = NULL;
lv_obj_t * ui_AppItemFlwPage01 = NULL;
lv_obj_t * ui_AppItemFlwPage02 = NULL;
lv_obj_t * ui_AppItemFlwPage03 = NULL;
lv_obj_t * ui_AppItemFlwPage04 = NULL;
lv_obj_t * ui_AppItemFlwPage05 = NULL;
lv_obj_t * ui_AppItemFlwPage06 = NULL;
lv_obj_t * ui_AppItemFlwPage07 = NULL;
lv_obj_t * ui_AppItemFlwPage08 = NULL;
lv_obj_t * ui_AppItemFlwPage09 = NULL;
lv_obj_t * ui_AppItemFlwPage10 = NULL;
lv_obj_t * ui_AppItemFlwPage11 = NULL;
lv_obj_t * ui_AppItemFlwPage12 = NULL;
// event funtions
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_FirstPage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_FollowingPage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_flag_modify(ui_FollowingPage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_FirstPage, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_AppItemSettings_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        videofocusmanager_open_app(APP_SETTINGS);
    }

}

void ui_event_AppItemBluetooth_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        /* Initialize Bluetooth lazily on first tap so it stays off the
         * startup/first-frame path. bt_app_init_async() is idempotent. */
#ifdef HCN_APP_HAVE_BT
        BtAppConfig bt_config = { "/data/bluetoothconfiguration.cfg" };
        bt_app_init_async(&bt_config);
#endif
        videofocusmanager_open_app(APP_BLUETOOTH);
    }
}

void ui_event_AppItemMusic_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        int ret = videofocusmanager_open_app(APP_MUSIC);
        syslog(LOG_INFO, "music app open requested, ret=%d", ret);
    }
}

void ui_event_AppItemPicture_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        int ret = videofocusmanager_open_app(APP_PICTURE);
        syslog(LOG_INFO, "picture app open requested, ret=%d", ret);
    }
}

void ui_event_AppItemVideo_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        int ret = videofocusmanager_open_app(APP_VIDEO);
        syslog(LOG_INFO, "video app open requested, ret=%d", ret);
    }
}

void ui_event_AppItemCarPlayApp_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    //lv_log("%s", __func__);

    if(event_code == LV_EVENT_PRESSED) {
#ifdef LVGL_BUILD_CARPLAY
        CarplayApp* cp = carplayapp_get_instance();
        if (carplayapp_is_connected(cp) && !carplayapp_is_show_limit(cp)) {
            videofocusmanager_open_app(APP_CARPLAY);
            carplayapp_request_ui(cp);
        }
#endif
    }
}

void ui_event_AppItemCarPlaySetting_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    //lv_log("%s", __func__);

    if(event_code == LV_EVENT_PRESSED) {
        videofocusmanager_open_app(APP_CARPLAY_SETTINGS);
    }
}

void ui_event_AppItemAndroidAuto_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        /* Initialize AndroidAuto lazily on first tap so it stays off the
         * startup/first-frame path. aa_app_init() is idempotent. */
#ifdef HCN_APP_HAVE_AA
        aa_app_init();
        aa_app_open_projection();
#endif
    }
}

void ui_event_AppItemAndroidAutoSettings_appItemImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
#ifdef HCN_APP_HAVE_AA
        aa_app_init();
        aa_app_open_settings();
#endif
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    //lv_obj_set_style_bg_image_src(ui_Home, &ui_img_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0XD8BFDB), 0);
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0XC0C0C0), 0);

    ui_ContainerHome = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_ContainerHome);
    lv_obj_set_width(ui_ContainerHome, lv_pct(100));
    lv_obj_set_height(ui_ContainerHome, lv_pct(100));
    lv_obj_set_align(ui_ContainerHome, LV_ALIGN_CENTER);

    ui_TopBarContainer = lv_obj_create(ui_ContainerHome);
    lv_obj_remove_style_all(ui_TopBarContainer);
    lv_obj_set_width(ui_TopBarContainer, 1024);
    lv_obj_set_height(ui_TopBarContainer, 56);
    lv_obj_set_align(ui_TopBarContainer, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_TopBarContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TopBarContainer, lv_color_hex(0x7BB191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopBarContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_bg_grad_color(ui_TopBarContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopBarContainer, lv_color_hex(0XA9A9A9), 0);

    ui_homepic = lv_button_create(ui_TopBarContainer);
    lv_obj_set_pos(ui_homepic, 14, 10);
    lv_obj_set_size(ui_homepic, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_style_radius(ui_homepic, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t* homeLabel = lv_label_create(ui_homepic);
    lv_label_set_text(homeLabel, "Home");
    lv_obj_center(homeLabel);

    ui_backpic = lv_button_create(ui_TopBarContainer);
    lv_obj_set_pos(ui_backpic, 941, 10);
    lv_obj_set_size(ui_backpic, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
    lv_obj_set_style_radius(ui_backpic, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_t* backLabel = lv_label_create(ui_backpic);
    lv_label_set_text(backLabel, "Back");
    lv_obj_center(backLabel);

    /*
    ui_homepic = lv_image_create(ui_TopBarContainer);
    lv_image_set_src(ui_homepic, &ui_img_home_png);
    lv_obj_set_width(ui_homepic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homepic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_homepic, 14);
    lv_obj_set_y(ui_homepic, 10);
    lv_obj_add_flag(ui_homepic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_homepic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_backpic = lv_image_create(ui_TopBarContainer);
    lv_image_set_src(ui_backpic, &ui_img_back_png);
    lv_obj_set_width(ui_backpic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_backpic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_backpic, -15);
    lv_obj_set_y(ui_backpic, 12);
    lv_obj_set_align(ui_backpic, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_backpic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_backpic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    */

    ui_FirstPage = lv_obj_create(ui_ContainerHome);
    lv_obj_remove_style_all(ui_FirstPage);
    lv_obj_set_width(ui_FirstPage, 1024);
    lv_obj_set_height(ui_FirstPage, 360);
    lv_obj_set_x(ui_FirstPage, 0);
    lv_obj_set_y(ui_FirstPage, -60);
    lv_obj_set_align(ui_FirstPage, LV_ALIGN_CENTER);

    ui_TimeAndDataContainer = lv_obj_create(ui_FirstPage);
    lv_obj_remove_style_all(ui_TimeAndDataContainer);
    lv_obj_set_width(ui_TimeAndDataContainer, 375);
    lv_obj_set_height(ui_TimeAndDataContainer, 147);
    lv_obj_set_x(ui_TimeAndDataContainer, -265);
    lv_obj_set_y(ui_TimeAndDataContainer, -68);
    lv_obj_set_align(ui_TimeAndDataContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TimeAndDataContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeAndDataContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeAndDataContainer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);


    //ui_TimeExt

    ui_textTime = lv_label_create(ui_TimeAndDataContainer);
    lv_obj_set_width(ui_textTime, 165);
    lv_obj_set_height(ui_textTime, 70);
    lv_obj_set_x(ui_textTime, -90);
    lv_obj_set_y(ui_textTime, -10);
    lv_obj_set_align(ui_textTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textTime, "08:01");
    lv_obj_set_style_text_color(ui_textTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_obj_set_style_text_align(ui_textTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textTime, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_textTime, 400, 0);

    /*
    ui_hourH = lv_image_create(ui_TimeAndDataContainer);
    lv_image_set_src(ui_hourH, &ui_img_1_png);
    lv_obj_set_width(ui_hourH, 35);
    lv_obj_set_height(ui_hourH, 70);
    lv_obj_set_x(ui_hourH, -154);
    lv_obj_set_y(ui_hourH, -2);
    lv_obj_set_align(ui_hourH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourH, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_hourH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourL = lv_image_create(ui_TimeAndDataContainer);
    lv_image_set_src(ui_hourL, &ui_img_0_png);
    lv_obj_set_width(ui_hourL, 35);
    lv_obj_set_height(ui_hourL, 70);
    lv_obj_set_x(ui_hourL, -107);
    lv_obj_set_y(ui_hourL, -2);
    lv_obj_set_align(ui_hourL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hourL, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_hourL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_minH = lv_image_create(ui_TimeAndDataContainer);
    lv_image_set_src(ui_minH, &ui_img_4_png);
    lv_obj_set_width(ui_minH, 35);
    lv_obj_set_height(ui_minH, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_minH, -38);
    lv_obj_set_y(ui_minH, -1);
    lv_obj_set_align(ui_minH, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minH, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_minH, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_minL = lv_image_create(ui_TimeAndDataContainer);
    lv_image_set_src(ui_minL, &ui_img_5_png);
    lv_obj_set_width(ui_minL, 35);
    lv_obj_set_height(ui_minL, 70);
    lv_obj_set_x(ui_minL, 13);
    lv_obj_set_y(ui_minL, -1);
    lv_obj_set_align(ui_minL, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_minL, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_minL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dot = lv_image_create(ui_TimeAndDataContainer);
    lv_image_set_src(ui_dot, &ui_img_clockslider_png);
    lv_obj_set_width(ui_dot, 35);
    lv_obj_set_height(ui_dot, 70);
    lv_obj_set_x(ui_dot, -64);
    lv_obj_set_y(ui_dot, -1);
    lv_obj_set_align(ui_dot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dot, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    */

    ui_textAMPM = lv_label_create(ui_TimeAndDataContainer);
    lv_obj_set_width(ui_textAMPM, 50);
    lv_obj_set_height(ui_textAMPM, 30);
    lv_obj_set_x(ui_textAMPM, 53);
    lv_obj_set_y(ui_textAMPM, -50);
    lv_obj_set_align(ui_textAMPM, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textAMPM, "PM");
    lv_obj_set_style_text_color(ui_textAMPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textAMPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textDay = lv_label_create(ui_TimeAndDataContainer);
    lv_obj_set_width(ui_textDay, 154);
    lv_obj_set_height(ui_textDay, 30);
    lv_obj_set_x(ui_textDay, 104);
    lv_obj_set_y(ui_textDay, -17);
    lv_obj_set_align(ui_textDay, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textDay, "Friday");
    lv_obj_set_style_text_color(ui_textDay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textDay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_textDay, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textDay, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textDate = lv_label_create(ui_TimeAndDataContainer);
    lv_obj_set_width(ui_textDate, 154);
    lv_obj_set_height(ui_textDate, 20);
    lv_obj_set_x(ui_textDate, 108);
    lv_obj_set_y(ui_textDate, 17);
    lv_obj_set_align(ui_textDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textDate, "2010-01-01");
    lv_obj_set_style_text_color(ui_textDate, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_textDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textDate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherContainer = lv_obj_create(ui_FirstPage);
    lv_obj_remove_style_all(ui_weatherContainer);
    lv_obj_set_width(ui_weatherContainer, 375);
    lv_obj_set_height(ui_weatherContainer, 147);
    lv_obj_set_x(ui_weatherContainer, 207);
    lv_obj_set_y(ui_weatherContainer, -68);
    lv_obj_set_align(ui_weatherContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weatherContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weatherContainer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    /*
    ui_ImageWeather = lv_image_create(ui_weatherContainer);
    lv_image_set_src(ui_ImageWeather, &ui_img_weather_cloudy_png);
    lv_obj_set_width(ui_ImageWeather, 135);
    lv_obj_set_height(ui_ImageWeather, 130);
    lv_obj_set_x(ui_ImageWeather, -108);
    lv_obj_set_y(ui_ImageWeather, -1);
    lv_obj_set_align(ui_ImageWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWeather, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageWeather, 180);
    */

    ui_textCity = lv_label_create(ui_weatherContainer);
    lv_obj_set_width(ui_textCity, 184);
    lv_obj_set_height(ui_textCity, 40);
    lv_obj_set_x(ui_textCity, 49);
    lv_obj_set_y(ui_textCity, -42);
    lv_obj_set_align(ui_textCity, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textCity, "ShenZhen");
    lv_obj_set_style_text_color(ui_textCity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textCity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textCity, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textWeather = lv_label_create(ui_weatherContainer);
    lv_obj_set_width(ui_textWeather, 180);
    lv_obj_set_height(ui_textWeather, 35);
    lv_obj_set_x(ui_textWeather, 49);
    lv_obj_set_y(ui_textWeather, 0);
    lv_obj_set_align(ui_textWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textWeather, "Cloudy");
    lv_obj_set_style_text_color(ui_textWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textWeather, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textTemperature = lv_label_create(ui_weatherContainer);
    lv_obj_set_width(ui_textTemperature, 180);
    lv_obj_set_height(ui_textTemperature, 35);
    lv_obj_set_x(ui_textTemperature, 49);
    lv_obj_set_y(ui_textTemperature, 42);
    lv_obj_set_align(ui_textTemperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textTemperature, "17°C~25°C");
    lv_obj_set_style_text_color(ui_textTemperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textTemperature, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppItemCarplaySettings = ui_AppItem_create(ui_FirstPage);
    lv_obj_set_x(ui_AppItemCarplaySettings, -412);
    lv_obj_set_y(ui_AppItemCarplaySettings, 100);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemCarplaySettings, UI_COMP_APPITEM_APPITEMIMAGE), 300);

    ui_AppItemCarplayApp = ui_AppItem_create(ui_FirstPage);
    lv_obj_set_x(ui_AppItemCarplayApp, -249);
    lv_obj_set_y(ui_AppItemCarplayApp, 100);

    lv_image_set_src(ui_comp_get_child(ui_AppItemCarplayApp, UI_COMP_APPITEM_APPITEMIMAGE), &ui_img_carplayapp_png);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemCarplayApp, UI_COMP_APPITEM_APPITEMIMAGE), 300);

    lv_label_set_text(ui_comp_get_child(ui_AppItemCarplayApp, UI_COMP_APPITEM_APPITEMTEXT), "CarPlay");

    ui_AppItemAndroidAutoSettings = ui_AppItem_create(ui_FirstPage);
    lv_obj_set_x(ui_AppItemAndroidAutoSettings, -85);
    lv_obj_set_y(ui_AppItemAndroidAutoSettings, 100);

    lv_image_set_src(ui_comp_get_child(ui_AppItemAndroidAutoSettings, UI_COMP_APPITEM_APPITEMIMAGE),
                     &ui_img_androidautosettings_png);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemAndroidAutoSettings, UI_COMP_APPITEM_APPITEMIMAGE), 300);

    lv_label_set_text(ui_comp_get_child(ui_AppItemAndroidAutoSettings, UI_COMP_APPITEM_APPITEMTEXT), "AndroidAutoSettings");
    lv_obj_set_style_text_font(ui_comp_get_child(ui_AppItemAndroidAutoSettings, UI_COMP_APPITEM_APPITEMTEXT),
                               &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppItemAndroidAuto = ui_AppItem_create(ui_FirstPage);
    lv_obj_set_x(ui_AppItemAndroidAuto, 85);
    lv_obj_set_y(ui_AppItemAndroidAuto, 100);

    lv_image_set_src(ui_comp_get_child(ui_AppItemAndroidAuto, UI_COMP_APPITEM_APPITEMIMAGE), &ui_img_androidautoapp_png);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemAndroidAuto, UI_COMP_APPITEM_APPITEMIMAGE), 300);

    lv_label_set_text(ui_comp_get_child(ui_AppItemAndroidAuto, UI_COMP_APPITEM_APPITEMTEXT), "AndroidAuto");

    ui_AppItemTemp01 = ui_AppItem_create(ui_FirstPage);
    lv_obj_set_x(ui_AppItemTemp01, 249);
    lv_obj_set_y(ui_AppItemTemp01, 100);
    lv_obj_add_flag(ui_AppItemTemp01, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemTemp02 = ui_AppItem_create(ui_FirstPage);
    lv_obj_set_x(ui_AppItemTemp02, 412);
    lv_obj_set_y(ui_AppItemTemp02, 100);
    lv_obj_add_flag(ui_AppItemTemp02, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_FixedPage = lv_obj_create(ui_ContainerHome);
    lv_obj_remove_style_all(ui_FixedPage);
    lv_obj_set_width(ui_FixedPage, 1024);
    lv_obj_set_height(ui_FixedPage, 180);
    lv_obj_set_x(ui_FixedPage, 0);
    lv_obj_set_y(ui_FixedPage, 200);
    lv_obj_set_align(ui_FixedPage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FixedPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AppItemVideo = ui_AppItem_create(ui_FixedPage);
    lv_obj_set_x(ui_AppItemVideo, -412);
    lv_obj_set_y(ui_AppItemVideo, 30);

    lv_image_set_src(ui_comp_get_child(ui_AppItemVideo, UI_COMP_APPITEM_APPITEMIMAGE), &ui_img_video_png);
    lv_obj_set_width(ui_comp_get_child(ui_AppItemVideo, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_obj_set_height(ui_comp_get_child(ui_AppItemVideo, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemVideo, UI_COMP_APPITEM_APPITEMIMAGE), 255);

    lv_label_set_text(ui_comp_get_child(ui_AppItemVideo, UI_COMP_APPITEM_APPITEMTEXT), "Video");

    ui_AppItemMusic = ui_AppItem_create(ui_FixedPage);
    lv_obj_set_x(ui_AppItemMusic, -249);
    lv_obj_set_y(ui_AppItemMusic, 30);

    lv_image_set_src(ui_comp_get_child(ui_AppItemMusic, UI_COMP_APPITEM_APPITEMIMAGE), &ui_img_music_png);
    lv_obj_set_width(ui_comp_get_child(ui_AppItemMusic, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_obj_set_height(ui_comp_get_child(ui_AppItemMusic, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemMusic, UI_COMP_APPITEM_APPITEMIMAGE), 255);

    lv_label_set_text(ui_comp_get_child(ui_AppItemMusic, UI_COMP_APPITEM_APPITEMTEXT), "Music");

    ui_AppItemPicture = ui_AppItem_create(ui_FixedPage);
    lv_obj_set_x(ui_AppItemPicture, -85);
    lv_obj_set_y(ui_AppItemPicture, 30);

    lv_image_set_src(ui_comp_get_child(ui_AppItemPicture, UI_COMP_APPITEM_APPITEMIMAGE), &ui_img_picture_png);
    lv_obj_set_width(ui_comp_get_child(ui_AppItemPicture, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_obj_set_height(ui_comp_get_child(ui_AppItemPicture, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemPicture, UI_COMP_APPITEM_APPITEMIMAGE), 255);

    lv_label_set_text(ui_comp_get_child(ui_AppItemPicture, UI_COMP_APPITEM_APPITEMTEXT), "Picture");

    ui_AppItemSettings = ui_AppItem_create(ui_FixedPage);
    lv_obj_set_x(ui_AppItemSettings, 85);
    lv_obj_set_y(ui_AppItemSettings, 30);

    lv_image_set_src(ui_comp_get_child(ui_AppItemSettings, UI_COMP_APPITEM_APPITEMIMAGE), &ui_img_setting_png);
    lv_obj_set_width(ui_comp_get_child(ui_AppItemSettings, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_obj_set_height(ui_comp_get_child(ui_AppItemSettings, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemSettings, UI_COMP_APPITEM_APPITEMIMAGE), 255);

    lv_label_set_text(ui_comp_get_child(ui_AppItemSettings, UI_COMP_APPITEM_APPITEMTEXT), "Settings");

    ui_AppItemBluetooth = ui_AppItem_create(ui_FixedPage);
    lv_obj_set_x(ui_AppItemBluetooth, 249);
    lv_obj_set_y(ui_AppItemBluetooth, 30);

    lv_image_set_src(ui_comp_get_child(ui_AppItemBluetooth, UI_COMP_APPITEM_APPITEMIMAGE), &ui_img_btcall_png);
    lv_obj_set_width(ui_comp_get_child(ui_AppItemBluetooth, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_obj_set_height(ui_comp_get_child(ui_AppItemBluetooth, UI_COMP_APPITEM_APPITEMIMAGE), 110);
    lv_image_set_scale(ui_comp_get_child(ui_AppItemBluetooth, UI_COMP_APPITEM_APPITEMIMAGE), 255);

    lv_label_set_text(ui_comp_get_child(ui_AppItemBluetooth, UI_COMP_APPITEM_APPITEMTEXT), "Bluetooth");

    ui_AppItemTemp04 = ui_AppItem_create(ui_FixedPage);
    lv_obj_set_x(ui_AppItemTemp04, 412);
    lv_obj_set_y(ui_AppItemTemp04, 30);
    lv_obj_add_flag(ui_AppItemTemp04, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_FollowingPage = lv_obj_create(ui_ContainerHome);
    lv_obj_remove_style_all(ui_FollowingPage);
    lv_obj_set_width(ui_FollowingPage, 1024);
    lv_obj_set_height(ui_FollowingPage, 360);
    lv_obj_set_x(ui_FollowingPage, 0);
    lv_obj_set_y(ui_FollowingPage, -60);
    lv_obj_set_align(ui_FollowingPage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FollowingPage, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_FollowingPage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AppItemFlwPage01 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage01, -412);
    lv_obj_set_y(ui_AppItemFlwPage01, -45);
    lv_obj_add_flag(ui_AppItemFlwPage01, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage02 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage02, -249);
    lv_obj_set_y(ui_AppItemFlwPage02, -45);
    lv_obj_add_flag(ui_AppItemFlwPage02, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage03 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage03, -85);
    lv_obj_set_y(ui_AppItemFlwPage03, -45);
    lv_obj_add_flag(ui_AppItemFlwPage03, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage04 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage04, 85);
    lv_obj_set_y(ui_AppItemFlwPage04, -45);
    lv_obj_add_flag(ui_AppItemFlwPage04, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage05 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage05, 249);
    lv_obj_set_y(ui_AppItemFlwPage05, -45);
    lv_obj_add_flag(ui_AppItemFlwPage05, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage06 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage06, 412);
    lv_obj_set_y(ui_AppItemFlwPage06, -45);
    lv_obj_add_flag(ui_AppItemFlwPage06, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage07 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage07, -412);
    lv_obj_set_y(ui_AppItemFlwPage07, 110);
    lv_obj_add_flag(ui_AppItemFlwPage07, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage08 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage08, -249);
    lv_obj_set_y(ui_AppItemFlwPage08, 110);
    lv_obj_add_flag(ui_AppItemFlwPage08, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage09 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage09, -85);
    lv_obj_set_y(ui_AppItemFlwPage09, 110);
    lv_obj_add_flag(ui_AppItemFlwPage09, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage10 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage10, 85);
    lv_obj_set_y(ui_AppItemFlwPage10, 110);
    lv_obj_add_flag(ui_AppItemFlwPage10, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage11 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage11, 249);
    lv_obj_set_y(ui_AppItemFlwPage11, 110);
    lv_obj_add_flag(ui_AppItemFlwPage11, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_AppItemFlwPage12 = ui_AppItem_create(ui_FollowingPage);
    lv_obj_set_x(ui_AppItemFlwPage12, 412);
    lv_obj_set_y(ui_AppItemFlwPage12, 110);
    lv_obj_add_flag(ui_AppItemFlwPage12, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemSettings, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemSettings_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemBluetooth, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemBluetooth_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemMusic, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemMusic_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemPicture, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemPicture_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemVideo, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemVideo_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemAndroidAuto, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemAndroidAuto_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemAndroidAutoSettings, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemAndroidAutoSettings_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemCarplayApp, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemCarPlayApp_appItemImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_AppItemCarplaySettings, UI_COMP_APPITEM_APPITEMIMAGE),
                        ui_event_AppItemCarPlaySetting_appItemImage, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);
    uic_Home = ui_Home;
    uic_ContainerHome = ui_ContainerHome;
    uic_TopBarContainer = ui_TopBarContainer;
    uic_home_picture = ui_homepic;
    uic_back_picture = ui_backpic;
    uic_FirstPage = ui_FirstPage;
    uic_TimeAndDataContainer = ui_TimeAndDataContainer;
    uic_hourH = ui_hourH;
    uic_hourL = ui_hourL;
    uic_minH = ui_minH;
    uic_minL = ui_minL;
    uic_dot = ui_dot;
    uic_textAMPM = ui_textAMPM;
    uic_textDay = ui_textDay;
    uic_textDate = ui_textDate;
    uic_weatherContainer = ui_weatherContainer;
    uic_textCity = ui_textCity;
    uic_textWeather = ui_textWeather;
    uic_textTemperature = ui_textTemperature;
    uic_AppItemCarplaySettings = ui_AppItemCarplaySettings;
    uic_AppItemCarplayApp = ui_AppItemCarplayApp;
    uic_AppItemAndroidAutoSettings = ui_AppItemAndroidAutoSettings;
    uic_AppItemAndroidAuto = ui_AppItemAndroidAuto;
    uic_AppItemTemp01 = ui_AppItemTemp01;
    uic_AppItemTemp02 = ui_AppItemTemp02;
    uic_FixedPage = ui_FixedPage;
    uic_AppItemVideo = ui_AppItemVideo;
    uic_AppItemMusic = ui_AppItemMusic;
    uic_AppItemPicture = ui_AppItemPicture;
    uic_AppItemSettings = ui_AppItemSettings;
    uic_AppItemBluetooth = ui_AppItemBluetooth;
    uic_AppItemTemp04 = ui_AppItemTemp04;
    uic_FollowingPage = ui_FollowingPage;
    uic_AppItemFlwPage01 = ui_AppItemFlwPage01;
    uic_AppItemFlwPage02 = ui_AppItemFlwPage02;
    uic_AppItemFlwPage03 = ui_AppItemFlwPage03;
    uic_AppItemFlwPage04 = ui_AppItemFlwPage04;
    uic_AppItemFlwPage05 = ui_AppItemFlwPage05;
    uic_AppItemFlwPage06 = ui_AppItemFlwPage06;
    uic_AppItemFlwPage07 = ui_AppItemFlwPage07;
    uic_AppItemFlwPage08 = ui_AppItemFlwPage08;
    uic_AppItemFlwPage09 = ui_AppItemFlwPage09;
    uic_AppItemFlwPage10 = ui_AppItemFlwPage10;
    uic_AppItemFlwPage11 = ui_AppItemFlwPage11;
    uic_AppItemFlwPage12 = ui_AppItemFlwPage12;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_Home = NULL;
    ui_Home = NULL;
    uic_ContainerHome = NULL;
    ui_ContainerHome = NULL;
    uic_TopBarContainer = NULL;
    ui_TopBarContainer = NULL;
    uic_home_picture = NULL;
    ui_homepic = NULL;
    uic_back_picture = NULL;
    ui_backpic = NULL;
    uic_FirstPage = NULL;
    ui_FirstPage = NULL;
    uic_TimeAndDataContainer = NULL;
    ui_TimeAndDataContainer = NULL;
    uic_hourH = NULL;
    ui_hourH = NULL;
    uic_hourL = NULL;
    ui_hourL = NULL;
    uic_minH = NULL;
    ui_minH = NULL;
    uic_minL = NULL;
    ui_minL = NULL;
    uic_dot = NULL;
    ui_dot = NULL;
    uic_textAMPM = NULL;
    ui_textAMPM = NULL;
    uic_textDay = NULL;
    ui_textDay = NULL;
    uic_textDate = NULL;
    ui_textDate = NULL;
    uic_weatherContainer = NULL;
    ui_weatherContainer = NULL;
    ui_ImageWeather = NULL;
    uic_textCity = NULL;
    ui_textCity = NULL;
    uic_textWeather = NULL;
    ui_textWeather = NULL;
    uic_textTemperature = NULL;
    ui_textTemperature = NULL;
    uic_AppItemCarplaySettings = NULL;
    ui_AppItemCarplaySettings = NULL;
    uic_AppItemCarplayApp = NULL;
    ui_AppItemCarplayApp = NULL;
    uic_AppItemAndroidAutoSettings = NULL;
    ui_AppItemAndroidAutoSettings = NULL;
    uic_AppItemAndroidAuto = NULL;
    ui_AppItemAndroidAuto = NULL;
    uic_AppItemTemp01 = NULL;
    ui_AppItemTemp01 = NULL;
    uic_AppItemTemp02 = NULL;
    ui_AppItemTemp02 = NULL;
    uic_FixedPage = NULL;
    ui_FixedPage = NULL;
    uic_AppItemVideo = NULL;
    ui_AppItemVideo = NULL;
    uic_AppItemMusic = NULL;
    ui_AppItemMusic = NULL;
    uic_AppItemPicture = NULL;
    ui_AppItemPicture = NULL;
    uic_AppItemSettings = NULL;
    ui_AppItemSettings = NULL;
    uic_AppItemBluetooth = NULL;
    ui_AppItemBluetooth = NULL;
    uic_AppItemTemp04 = NULL;
    ui_AppItemTemp04 = NULL;
    uic_FollowingPage = NULL;
    ui_FollowingPage = NULL;
    uic_AppItemFlwPage01 = NULL;
    ui_AppItemFlwPage01 = NULL;
    uic_AppItemFlwPage02 = NULL;
    ui_AppItemFlwPage02 = NULL;
    uic_AppItemFlwPage03 = NULL;
    ui_AppItemFlwPage03 = NULL;
    uic_AppItemFlwPage04 = NULL;
    ui_AppItemFlwPage04 = NULL;
    uic_AppItemFlwPage05 = NULL;
    ui_AppItemFlwPage05 = NULL;
    uic_AppItemFlwPage06 = NULL;
    ui_AppItemFlwPage06 = NULL;
    uic_AppItemFlwPage07 = NULL;
    ui_AppItemFlwPage07 = NULL;
    uic_AppItemFlwPage08 = NULL;
    ui_AppItemFlwPage08 = NULL;
    uic_AppItemFlwPage09 = NULL;
    ui_AppItemFlwPage09 = NULL;
    uic_AppItemFlwPage10 = NULL;
    ui_AppItemFlwPage10 = NULL;
    uic_AppItemFlwPage11 = NULL;
    ui_AppItemFlwPage11 = NULL;
    uic_AppItemFlwPage12 = NULL;
    ui_AppItemFlwPage12 = NULL;

}
