// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_ContainerHome;
extern lv_obj_t * ui_TopBarContainer;
extern lv_obj_t * ui_homepic;
extern lv_obj_t * ui_backpic;
extern lv_obj_t * ui_FirstPage;
extern lv_obj_t * ui_TimeAndDataContainer;
extern lv_obj_t * ui_hourH;
extern lv_obj_t * ui_hourL;
extern lv_obj_t * ui_minH;
extern lv_obj_t * ui_minL;
extern lv_obj_t * ui_dot;
extern lv_obj_t * ui_textAMPM;
extern lv_obj_t * ui_textDay;
extern lv_obj_t * ui_textDate;
extern lv_obj_t * ui_weatherContainer;
extern lv_obj_t * ui_ImageWeather;
extern lv_obj_t * ui_textCity;
extern lv_obj_t * ui_textWeather;
extern lv_obj_t * ui_textTemperature;
extern lv_obj_t * ui_AppItemCarplaySettings;
extern lv_obj_t * ui_AppItemCarplayApp;

extern void ui_event_AppItemCarPlayApp_appItemImage(lv_event_t * e);
extern void ui_event_AppItemCarPlaySetting_appItemImage(lv_event_t * e);

extern lv_obj_t * ui_AppItemAndroidAutoSettings;
extern lv_obj_t * ui_AppItemAndroidAuto;
extern lv_obj_t * ui_AppItemTemp01;
extern lv_obj_t * ui_AppItemTemp02;
extern lv_obj_t * ui_FixedPage;
extern lv_obj_t * ui_AppItemVideo;
extern void ui_event_AppItemVideo_appItemImage(lv_event_t * e);
extern lv_obj_t * ui_AppItemMusic;
extern void ui_event_AppItemMusic_appItemImage(lv_event_t * e);
extern lv_obj_t * ui_AppItemPicture;
extern void ui_event_AppItemPicture_appItemImage(lv_event_t * e);
extern lv_obj_t * ui_AppItemSettings;
extern void ui_event_AppItemSettings_appItemImage(lv_event_t * e);
extern lv_obj_t * ui_AppItemBluetooth;
extern void ui_event_AppItemBluetooth_appItemImage(lv_event_t * e);
extern lv_obj_t * ui_AppItemTemp04;
extern lv_obj_t * ui_FollowingPage;
extern lv_obj_t * ui_AppItemFlwPage01;
extern lv_obj_t * ui_AppItemFlwPage02;
extern lv_obj_t * ui_AppItemFlwPage03;
extern lv_obj_t * ui_AppItemFlwPage04;
extern lv_obj_t * ui_AppItemFlwPage05;
extern lv_obj_t * ui_AppItemFlwPage06;
extern lv_obj_t * ui_AppItemFlwPage07;
extern lv_obj_t * ui_AppItemFlwPage08;
extern lv_obj_t * ui_AppItemFlwPage09;
extern lv_obj_t * ui_AppItemFlwPage10;
extern lv_obj_t * ui_AppItemFlwPage11;
extern lv_obj_t * ui_AppItemFlwPage12;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Home;
extern lv_obj_t * uic_ContainerHome;
extern lv_obj_t * uic_TopBarContainer;
extern lv_obj_t * uic_home_picture;
extern lv_obj_t * uic_back_picture;
extern lv_obj_t * uic_FirstPage;
extern lv_obj_t * uic_TimeAndDataContainer;
extern lv_obj_t * uic_hourH;
extern lv_obj_t * uic_hourL;
extern lv_obj_t * uic_minH;
extern lv_obj_t * uic_minL;
extern lv_obj_t * uic_dot;
extern lv_obj_t * uic_textAMPM;
extern lv_obj_t * uic_textDay;
extern lv_obj_t * uic_textDate;
extern lv_obj_t * uic_weatherContainer;
extern lv_obj_t * uic_textCity;
extern lv_obj_t * uic_textWeather;
extern lv_obj_t * uic_textTemperature;
extern lv_obj_t * uic_AppItemCarplaySettings;
extern lv_obj_t * uic_AppItemCarplayApp;
extern lv_obj_t * uic_AppItemAndroidAutoSettings;
extern lv_obj_t * uic_AppItemAndroidAuto;
extern lv_obj_t * uic_AppItemTemp01;
extern lv_obj_t * uic_AppItemTemp02;
extern lv_obj_t * uic_FixedPage;
extern lv_obj_t * uic_AppItemVideo;
extern lv_obj_t * uic_AppItemMusic;
extern lv_obj_t * uic_AppItemPicture;
extern lv_obj_t * uic_AppItemSettings;
extern lv_obj_t * uic_AppItemBluetooth;
extern lv_obj_t * uic_AppItemTemp04;
extern lv_obj_t * uic_FollowingPage;
extern lv_obj_t * uic_AppItemFlwPage01;
extern lv_obj_t * uic_AppItemFlwPage02;
extern lv_obj_t * uic_AppItemFlwPage03;
extern lv_obj_t * uic_AppItemFlwPage04;
extern lv_obj_t * uic_AppItemFlwPage05;
extern lv_obj_t * uic_AppItemFlwPage06;
extern lv_obj_t * uic_AppItemFlwPage07;
extern lv_obj_t * uic_AppItemFlwPage08;
extern lv_obj_t * uic_AppItemFlwPage09;
extern lv_obj_t * uic_AppItemFlwPage10;
extern lv_obj_t * uic_AppItemFlwPage11;
extern lv_obj_t * uic_AppItemFlwPage12;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
